### ISSUE TITLE
TypeError: i.$setDirty is not a function

### ISSUE THREAD

**Issue by wirasto** [mbenford/ngTagsInput#517]
This message always show in console log when add or remove item.

TypeError: i.$setDirty is not a function
    at http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:4722
    at d.factory.b.handleUndefinedResult (http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:13154)
    at http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:13609
    at Array.every (native)
    at Object.d.factory.b.simplePubSub.trigger (http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:13555)
    at Object.d.directive.i.add (http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:879)
    at Object.d.directive.i.addText (http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:744)
    at http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:5568
    at d.factory.b.handleUndefinedResult (http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:13154)
    at http://127.0.0.1:8000/assets/vendor/tags_input/ng-tags-input.min.js:1:13609

**Comment by asoesilo** [comment]
I see the same problem in `v3.0.0`, so I downgraded to `v2.3.0` and it works.

**Comment by asoesilo** [comment]
I found out the problem was because .setDirty() is only supported post Angular v1.3.3. Upgrading my Angular to v1.3.4 fixes the problem.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

@asoesilo You're right. From version 3.0.0 on ngTagsInput requires Angular 1.3. That issue should be fixed by using the correct version of Angular.

**Comment by simonv3** [comment]
I'm getting this error for angular 1.5.0.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
